Guardia Comunal/Models/Permission.cs
using Guardia_Comunal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GuardiaComunal.Models
{
    public class Permission
    {
        public int Id { get; set; }

        public int WindowId { get; set; }
        public virtual Window Window { get; set; }

        public int RolId { get; set; }
        public virtual Rol Role { get; set; }
        public bool Consulta { get; set; }
        public bool AltaModificacion { get; set; }
        public bool Baja { get; set; }
        public DateTime Fecha { get; set; }

        public List<Permission> Obtener(int Rolid)
        {

            using (var ctx = new ApplicationDbContext())
            {
                List<Permission> permiso = ctx.Permissions.Where(x => x.RolId == Rolid).ToList();

                return permiso;

            }
        }


    }
}

Guardia Comunal/Controllers/PermissionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GuardiaComunal.Models;
using Guardia_Comunal.Models;
using Newtonsoft.Json;
using Guardia_Comunal.Helpers;
using Guardia_Comunal.Tags;
using Guardia_Comunal.ViewModel;

namespace Guardia_Comunal.Controllers
{
    [AutenticadoAttribute]
    public class PermissionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public string ModuleDescription = "Configuración";
        public string WindowDescription = "Permisos";

        // GET: Permissions
        public ActionResult Index()
        {
            ViewBag.AltaModificacion = PermissionViewModel.TienePermisoAlta(WindowHelper.GetWindowId(ModuleDescription, WindowDescription));
            ViewBag.Baja = PermissionViewModel.TienePermisoBaja(WindowHelper.GetWindowId(ModuleDescription, WindowDescription));
            List<Permission> list = db.Permissions.ToList();
            List<Rol> lRoles = new List<Rol>();
            lRoles = db.Rols.Where(x => x.Nombre != "Administrador").ToList();
            ViewBag.listaRoles = lRoles;
            //return View(db.Permissions.ToList());
            return View(list);
        }

        [HttpPost]
        public JsonResult GetPermisos(int Rolid )
        {
            List<Permission> list = new List<Permission>();
            try
            {
                list = db.Permissions.ToList().Where(x => x.RolId == Rolid).ToList();

                //foreach (var item in list)
                //{
                //    item.Window.Module = db.Modules.Find(item.Window.M);
                //}

                return Json(list, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public JsonResult EditPermiso(int id, string tipo, bool permiso )
        {
            if (tipo == null || id == 0)
            {
                return Json(new { responseCode = "-10" });
            }

            Permission permission = db.Permissions.Find(id);

            switch (tipo)
            {
                case "Consulta":
                    permission.Consulta = permiso;
                    break;
                case "AltaModificacion":
                    permission.AltaModificacion = permiso;
                    break;
                case "Baja":
                    permission.Baja = permiso;
                    break;
                default:
                    break;
            }


            db.Entry(permission).State = EntityState.Modified;
            db.SaveChanges();

            //Audito
            AuditHelper.Auditar("Modificacion", permission.Id.ToString(), "Permission", ModuleDescription, WindowDescription);

            var responseObject = new
            {
                responseCode = 0
            };

            return Json(responseObject);
        }

        [HttpPost]
        public JsonResult UpdatePermisos(int idRol, string tipo, bool permiso)
        {
            if (tipo == null || idRol == 0)
            {
                return Json(new { responseCode = "-10" });
            }

            List<Permission> lista = db.Permissions.Where(x => x.RolId == idRol).ToList();

            if (lista != null)
            {
                foreach (var item in lista)
                {
                    switch (tipo)
                    {
                        case "Consulta":
                            item.Consulta = permiso;
                            break;
                        case "AltaModificacion":
                            item.AltaModificacion = permiso;
                            break;
                        case "Baja":
                            item.Baja = permiso;
                            break;
                        default:
                            break;
                    }

                    db.Entry(item).State = EntityState.Modified;
                }
                
                db.SaveChanges();

            }
            var responseObject = new
            {
                responseCode = 0
            };

            return Json(responseObject);
        }

        // GET: Permissions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permission permission = db.Permissions.Find(id);
            if (permission == null)
            {
                return HttpNotFound();
            }
            return View(permission);
        }

        // GET: Permissions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Permissions/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Consulta,AltaModificacion,Baja,Fecha")] Permission permission)
        {
            if (ModelState.IsValid)
            {
                db.Permissions.Add(permission);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(permission);
        }

        // GET: Permissions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permission permission = db.Permissions.Find(id);
            if (permission == null)
            {
                return HttpNotFound();
            }
            return View(permission);
        }

        // POST: Permissions/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Consulta,AltaModificacion,Baja,Fecha")] Permission permission)
        {
            if (ModelState.IsValid)
            {
                db.Entry(permission).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(permission);
        }

        // GET: Permissions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permission permission = db.Permissions.Find(id);
            if (permission == null)
            {
                return HttpNotFound();
            }
            return View(permission);
        }

        // POST: Permissions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Permission permission = db.Permissions.Find(id);
            db.Permissions.Remove(permission);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Guardia Comunal/Views/Permissions/Index.cshtml
@model IEnumerable<GuardiaComunal.Models.Permission>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Permisos</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <form class="form-horizontal">
                        <div class="form-inline">
                            <label style="display: initial" class="control-label">Roles</label>
                            @Html.DropDownList("selectRolCreate", new SelectList(ViewBag.listaRoles, "RolId", "Nombre"), htmlAttributes:
                            new
                            {
                                id = "selectRolCreate",
                                @class = "form-control",
                                @onchange = "refreshdropdown()"
                            }
                            )

                        </div>
                    </form>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Modulo</th>
                                <th>Pantalla</th>
                                <th><input type="checkbox" name="ckConsultaAll" id="ckConsultaAll" value="checked" /> Consulta</th>
                                <th><input type="checkbox" name="ckAltaModificacionAll" id="ckAltaModificacionAll" value="checked" /> Alta/Modif</th>
                                <th><input type="checkbox" name="ckBajaAll" id="ckBajaAll" value="checked" /> Baja</th>
                            </tr>
                        </thead>
                        <tbody>
                            @*@foreach (var item in Model)
                            {
                                <tr class="odd gradeX">
                                    <td>@item.Id</td>
                                    <td>@item.Window.Module.Descripcion</td>
                                    <td>@item.Window.Descripcion</td>
                                    <td class="center"><input name="consulta" value="1" type="checkbox"></td>
                                    <td class="center"><input name="altamodif" value="1" type="checkbox"></td>
                                    <td class="center"><input name="baja" value="1" type="checkbox"></td>
                                </tr>
                            }*@
                            </tbody>
                    </table>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->
    </div>
<!-- /#wrapper -->

@section scripts {
    <script>


        function refreshdropdown() {             
            //var RolId = $('#selectRolCreate').val();
            //$("#dataTables-example").dataTable().fnReloadAjax();
            var newurl = "@Url.Action("GetPermisos", "Permissions", new { Rolid = "ParamRolId" })".replace("ParamRolId", $('#selectRolCreate').val());
            $("#dataTables-example").dataTable().fnReloadAjax(newurl);
        

            };



        $(document).ready(function () {
            var AltaModificacion = '@ViewBag.AltaModificacion';

            if (AltaModificacion == 'False') {
                $('#ckConsultaAll').prop("disabled", true);
                $('#ckAltaModificacionAll').prop("disabled", true);
                $('#ckBajaAll').prop("disabled", true);
                //$('#dataTables-example .ConsultaCheckbox').prop("disabled", true);
                //$('#dataTables-example .AltaModificacionCheckbox').prop("disabled", true);
                //$('#dataTables-example .BajaCheckbox').prop("disabled", true);
            }



            $('#ckConsultaAll').change(function () {
                var RolId = $('#selectRolCreate').val();
                var Permiso_check = this.checked;

                if (this.checked) {
                    $('#dataTables-example .ConsultaCheckbox').prop('checked', true);                    
                }
                else {
                    $('#dataTables-example .ConsultaCheckbox').prop('checked', false);
                }
                UpdatePermisos(RolId, 'Consulta', Permiso_check);
            });

            $('#ckAltaModificacionAll').change(function () {
                var RolId = $('#selectRolCreate').val();
                var Permiso_check = this.checked;

                if (this.checked) {
                    $('#dataTables-example .AltaModificacionCheckbox').prop('checked', true);
                }
                else {
                    $('#dataTables-example .AltaModificacionCheckbox').prop('checked', false);
                }
                UpdatePermisos(RolId, 'AltaModificacion', Permiso_check);
            });


            $('#ckBajaAll').change(function () {
                var RolId = $('#selectRolCreate').val();
                var Permiso_check = this.checked;

                if (this.checked) {
                    $('#dataTables-example .BajaCheckbox').prop('checked', true);
                }
                else {
                    $('#dataTables-example .BajaCheckbox').prop('checked', false);
                }
                UpdatePermisos(RolId, 'Baja', Permiso_check);
            });




            $(document).on('click', '.ConsultaCheckbox', function () {
                if (AltaModificacion == 'True') {
                    var Permiso_id = $(this).parents('tr').attr('Id');
                    var Permiso_check = this.checked;
                    EditPermiso(Permiso_id, "Consulta", Permiso_check);
                }
            });

            $(document).on('click', '.AltaModificacionCheckbox', function () {
                if (AltaModificacion == 'True') {
                    var Permiso_id = $(this).parents('tr').attr('Id');
                    var Permiso_check = this.checked;
                    EditPermiso(Permiso_id, "AltaModificacion", Permiso_check);
                }
            });

            $(document).on('click', '.BajaCheckbox', function () {
                if (AltaModificacion == 'True') {
                    var Permiso_id = $(this).parents('tr').attr('Id');
                    var Permiso_check = this.checked;
                    EditPermiso(Permiso_id, "Baja", Permiso_check);
                }
            });

            function EditPermiso(Permiso_id, tipo, Permiso_check) {
                                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("EditPermiso")',
                    data: JSON.stringify({
                        id: Permiso_id,
                        tipo: tipo,
                        permiso: Permiso_check
                    }),
                        contentType: 'application/json; charset=utf-8',
                        dataType: 'json',
                        success: function (dataResponse) {
                            if (dataResponse.responseCode == 0)
                                {
                                Lobibox.notify('success', {
                                    title: 'Exito',
                                    msg: 'Los cambios se han grabado correctamente.'
                                });
                            } else {
                                    Lobibox.notify('error', {
                                        title: 'Error',
                                        msg: 'Ah ocurrido un error, intente nuevamente.'
                                });
                            }
                        },
                        error: function (response) {
                                Lobibox.notify('error', {
                                    title: 'Error',
                                    msg: 'Ah ocurrido un error, intente nuevamente.'
                                });
                        }
                    });
            }


            function UpdatePermisos(Rol, tipo, Permiso_check) {
                                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("UpdatePermisos")',
                    data: JSON.stringify({
                        idRol: Rol,
                        tipo: tipo,
                        permiso: Permiso_check
                    }),
                        contentType: 'application/json; charset=utf-8',
                        dataType: 'json',
                        success: function (dataResponse) {
                            if (dataResponse.responseCode == 0)
                                {
                                Lobibox.notify('success', {
                                    title: 'Exito',
                                    msg: 'Los cambios se han grabado correctamente.'
                                });
                            } else {
                                    Lobibox.notify('error', {
                                        title: 'Error',
                                        msg: 'Ah ocurrido un error, intente nuevamente.'
                                });
                            }
                        },
                        error: function (response) {
                                Lobibox.notify('error', {
                                    title: 'Error',
                                    msg: 'Ah ocurrido un error, intente nuevamente.'
                                });
                        }
                    });
            }

            var table = $('#dataTables-example').DataTable({
                 "ajax":
                  {
                     url: "@Url.Action("GetPermisos", "Permissions", new { Rolid = "ParamRolId" })".replace("ParamRolId", $('#selectRolCreate').val()),
                      type: "post",
                      dataSrc: ""
                },
                 "columns": [
                     { "data": "Id" },
                     { "data": "Window.Module.Descripcion" },
                     { "data": "Window.Descripcion" },
                     { "data": null, defaultContent: '' },
                     { "data": null, defaultContent: ''},
                     { "data": null, defaultContent: '' }

                 ],
                "columnDefs": [
                    { "visible": false, "targets": 1 }
                ],
                "ordering": false,
                rowId: 'Id',
                "displayLength": 25,
                "fnCreatedRow": function (nRow, aData, iDataIndex) {
                    if (aData.Consulta)
                    {
                        $('td:eq(2)', nRow).append("<input class='ConsultaCheckbox' name='consulta' type='checkbox' checked>");
                    }
                    else
                    {
                        $('td:eq(2)', nRow).append("<input class='ConsultaCheckbox' name='consulta' type='checkbox'>");
                    }

                    if (aData.AltaModificacion) {
                        $('td:eq(3)', nRow).append("<input class='AltaModificacionCheckbox' name='AltaModificacion' type='checkbox' checked>");
                    }
                    else {
                        $('td:eq(3)', nRow).append("<input class='AltaModificacionCheckbox' name='AltaModificacion' type='checkbox'>");
                    }
                    if (aData.Baja) {
                        $('td:eq(4)', nRow).append("<input class='AltaModificacionCheckbox' name='Baja' type='checkbox' checked>");
                    }
                    else {
                        $('td:eq(4)', nRow).append("<input class='BajaCheckbox'  name='Baja' type='checkbox'>");
                    }
                    
                },
                "drawCallback": function (settings) {
                    var api = this.api();
                    var rows = api.rows({ page: 'current' }).nodes();
                    var last = null;

                    api.column(1, { page: 'current' }).data().each(function (group, i) {
                        if (last !== group) {
                            $(rows).eq(i).before(
                                '<tr class="group"><td colspan="5" style="color: gray; font-weight: bold;">' + group + '</td></tr>'
                            );

                            last = group;
                        }
                    });
                }
            });

        });




    </script>

}