Guardia Comunal/Models/Act.cs
using ExpressiveAnnotations.Attributes;
using Guardia_Comunal.Validations;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Script.Serialization;

namespace GuardiaComunal.Models
{
    public class Act
    {

        // -----------Datos del Acta
        public int Id { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Requerido")]
        public string TipoDeActa { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Requerido")]
        public string NroActa { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Requerido")]
        public DateTime FechaInfraccion { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Requerido")]
        public Int32 Tanda { get; set; }

        //La descripcion de la calle la guardo por si no la encuentra en el maestro

        [Required(AllowEmptyStrings = false, ErrorMessage = "Requerido")]
        public string Calle { get; set; }
        //Este es el codigo de geolocalizacion
        public int? StreetId { get; set; }
        public virtual Street Street { get; set; }

        public string Altura { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Requerido")]
        public string EntreCalle { get; set; }

        //La descripcion del barrio la guardo por si no la encuentra en el maestro
        [Required(AllowEmptyStrings = false, ErrorMessage = "Requerido")]
        public string Barrio { get; set; }

        public int? NighborhoodId { get; set; }
        public virtual Nighborhood Nighborhood { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Requerido")]
      //  [DateGreaterThan("FechaInfraccion", "Estimated end date must be greater than the start date of the project")]
        public DateTime FechaEnvioAlJuzgado { get; set; }
        public string ActaAdjunta { get; set; }

        [NotMapped]
        public virtual bool ActaAdjuntaBorrada { get; set; }
        public DateTime FechaCarga { get; set; }

        public int UsuarioId { get; set; }
        public virtual Usuario Usuario { get; set; }

        // -----------Datos del Vehiculo

        [RequiredIf("TipoDeActa == 'Documentada'", ErrorMessage = "Requerido")]
        public string DNI { get; set; }
        [RequiredIf("TipoDeActa == 'Documentada'", ErrorMessage = "Requerido")]
        public string Nombre { get; set; }
        [RequiredIf("TipoDeActa == 'Documentada'", ErrorMessage = "Requerido")]
        public string Apellido { get; set; }

        [RequiredIf("LicenciaRetenida == true", ErrorMessage = "Requerido")]
        public string NroLicencia { get; set; }

        // -----------Datos del Vehiculo
        [Required(AllowEmptyStrings = false, ErrorMessage = "Requerido")]
        public int VehicleTypeId { get; set; }
        public virtual VehicleType VehicleType { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Requerido")]
        public int DomainId { get; set; }

        public virtual Domain Domain { get; set; }

        public string Dominio { get; set; }
        public int? VehicleBrandId { get; set; }
        public virtual VehicleBrand VehicleBrand { get; set; }


        public int? VehicleModelId { get; set; }
        public virtual VehicleModel VehicleModel { get; set; }
        public string Color { get; set; }
        public string NroMotor { get; set; }
        public string NroChasis { get; set; }
        public string EstadoVehiculo { get; set; }
        public DateTime FechaEstado { get; set; }

        // -----------Datos del Acta
        [Required(AllowEmptyStrings = false, ErrorMessage = "Requerido")]
        public string TipoAgente { get; set; }

        public int? InspectorId { get; set; }
        public virtual Inspector Inspector { get; set; }

        public string Policia { get; set; }
        public int? PoliceId  { get; set; }
        public virtual Police Police { get; set; }
        public bool VehiculoRetenido { get; set; }
        public bool LicenciaRetenida { get; set; }
        public bool TicketAlcoholemia { get; set; }

        [RequiredIf("TicketAlcoholemia == true", ErrorMessage = "Requerido")]
        public string ResultadoAlcoholemia { get; set; }
       
        public string TicketAlcoholemiaAdjunto { get; set; }
        [NotMapped]
        public virtual bool TicketAlcoholemiaAdjuntoBorrado { get; set; }
        
        public string Informe { get; set; }
        public string InformeAdjunto { get; set; }

        [NotMapped]
        public virtual bool InformeAdjuntoBorrado { get; set; }

        [ScriptIgnore]
        public virtual ICollection<Contravention> Contraventions { get; set; }


        public virtual int[] SelectedContraventions { get; set; }

        public virtual ICollection<Observation> Observations { get; set; }
        public virtual int[] SelectedObservations { get; set; }
        public string Detalle { get; set; }
        public bool Enable { get; set; }


    }
}

Guardia Comunal/Controllers/ActsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GuardiaComunal.Models;
using Guardia_Comunal.Models;
using Guardia_Comunal.Tags;
using Newtonsoft.Json;
using System.IO;
using Guardia_Comunal.ViewModel;
using Guardia_Comunal.Helpers;

namespace Guardia_Comunal.Controllers
{
    [AutenticadoAttribute]
    public class ActsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public string ModuleDescription = "Actas";
        public string WindowDescription = "Altas";

        // GET: Acts
        public ActionResult Index()
        {
          //   List<Act> list = db.Acts.Where(x=>x.Enable==true).ToList();
            ViewBag.AltaModificacion = PermissionViewModel.TienePermisoAlta(WindowHelper.GetWindowId("Actas", "Altas"));
            ViewBag.Baja = PermissionViewModel.TienePermisoBaja(WindowHelper.GetWindowId("Actas", "Baja"));
            ViewBag.Liberacion = PermissionViewModel.TienePermisoAlta(WindowHelper.GetWindowId("Actas", "Liberacion"));
            return View();
        }

        //public ActionResult Search(string NroActa)
        //{
        //    //  List<Act> list = db.Acts.Where(x => x.Enable == true && x.NroActa==NroActa).ToList();

        //    List<Act> list = db.Acts.Where(x => x.Enable == true && x.NroActa == NroActa).ToList();

        //    ViewBag.AltaModificacion = PermissionViewModel.TienePermisoAlta(WindowHelper.GetWindowId("Actas", "Altas"));
        //    ViewBag.Baja = PermissionViewModel.TienePermisoBaja(WindowHelper.GetWindowId("Actas", "Baja"));
        //    ViewBag.Liberacion = PermissionViewModel.TienePermisoAlta(WindowHelper.GetWindowId("Actas", "Liberacion"));
        //    ViewBag.NroActa = NroActa;
        //    return View(list);
        //}

        public ActionResult SearchNroActa(string NroActa)
        {
            List<ActIndexViewModel> acts = new List<ActIndexViewModel>();
            acts = ArmarConsulta(NroActa, null, null, null, null, null, null, null, null);
            ViewBag.AltaModificacion = PermissionViewModel.TienePermisoAlta(WindowHelper.GetWindowId("Actas", "Altas"));
            ViewBag.Baja = PermissionViewModel.TienePermisoBaja(WindowHelper.GetWindowId("Actas", "Baja"));
            ViewBag.Liberacion = PermissionViewModel.TienePermisoAlta(WindowHelper.GetWindowId("Actas", "Liberacion"));
            ViewBag.NroActa = NroActa;
            return View("Index",acts);
        }
        

        private List<ActIndexViewModel> ArmarConsulta(string NroActa, string NroLiberacion, string Estado, string DNI, string Apellido, string Nombre, string Dominio, string FechaDesde, string FechaHasta)
        {
            List<ActIndexViewModel> acts = new List<ActIndexViewModel>();
            DateTime? dtFechaDesde = null;
            DateTime? dtFechaHasta = null;

            if (!String.IsNullOrEmpty(FechaDesde))
                dtFechaDesde = Convert.ToDateTime(FechaDesde);

            if (!String.IsNullOrEmpty(FechaHasta))
                dtFechaHasta = Convert.ToDateTime(FechaHasta);


            try
            {

                List<Liberation> liberationsList = new List<Liberation>();


                var lista = db.Acts
                .Where(x => x.Enable == true)
                .Where(x => !string.IsNullOrEmpty(NroActa) ? (x.NroActa == NroActa && x.NroActa != null) : true)
                .Where(x => !string.IsNullOrEmpty(Estado) ? (x.EstadoVehiculo == Estado && x.EstadoVehiculo != null) : true)
                .Where(x => !string.IsNullOrEmpty(DNI) ? (x.DNI == DNI && x.DNI != null  || (db.Liberations.Where(y => y.ActaId == x.Id && y.Person.DNI == DNI).Any())) : true)
                .Where(x => !string.IsNullOrEmpty(Apellido) ? (x.Apellido == Apellido && x.Apellido != null) : true)
                .Where(x => !string.IsNullOrEmpty(Nombre) ? (x.Nombre == Nombre && x.Nombre != null) : true)
                .Where(x => !string.IsNullOrEmpty(Dominio) ? (x.Dominio == Dominio && x.Dominio != null) : true)
                .Where(x => !string.IsNullOrEmpty(FechaDesde) ? (x.FechaInfraccion >= dtFechaDesde && x.FechaInfraccion != null) : true)
                .Where(x => !string.IsNullOrEmpty(FechaHasta) ? (x.FechaInfraccion <= dtFechaHasta && x.FechaInfraccion != null) : true)
                .Where(x => !string.IsNullOrEmpty(NroLiberacion) ? (db.Liberations.Where(y => y.ActaId == x.Id && y.NroLiberacion == NroLiberacion).Any()) : true)
                .Select(c => new { c.Id, c.FechaCarga, c.FechaInfraccion, c.NroActa, c.Dominio, c.EstadoVehiculo, c.DNI, c.Nombre, c.Apellido }).OrderByDescending(x => x.FechaInfraccion).Take(1000);
                ;





                // List<ActIndexViewModel> acts = new List<ActIndexViewModel>();
                var liberations = db.Liberations.Where(x => x.Enable == true).ToList();

                foreach (var item in lista)
                {
                    ActIndexViewModel act = new ActIndexViewModel();
                    Liberation liberation = new Liberation();

                    //Busco si tiene un liberacion
                    liberation = liberations.Where(x => x.ActaId == item.Id).FirstOrDefault();

                    act.Id = item.Id;
                    act.NroActa = item.NroActa;
                    if (liberation != null)
                        act.NroLiberacion = liberation.NroLiberacion;

                    act.Apellido = item.Apellido;
                    act.DNI = item.DNI;
                    act.Dominio = item.Dominio;
                    act.Estado = item.EstadoVehiculo;
                    act.FechaCarga = item.FechaCarga;
                    act.FechaInfraccion = item.FechaInfraccion;

                    acts.Add(act);

                }

            }
            catch (Exception e)
            {

                throw;
            }

            return acts;
        }

        public JsonResult Search(string NroActa, string NroLiberacion, string Estado, string DNI, string Apellido, string Nombre, string Dominio, string FechaDesde, string FechaHasta )
        {

            List<ActIndexViewModel> acts = new List<ActIndexViewModel>();
            acts = ArmarConsulta(NroActa, NroLiberacion, Estado, DNI, Apellido, Nombre, Dominio, FechaDesde, FechaHasta);

            ViewBag.AltaModificacion = PermissionViewModel.TienePermisoAlta(WindowHelper.GetWindowId("Actas", "Altas"));
            ViewBag.Baja = PermissionViewModel.TienePermisoBaja(WindowHelper.GetWindowId("Actas", "Baja"));
            ViewBag.Liberacion = PermissionViewModel.TienePermisoAlta(WindowHelper.GetWindowId("Actas", "Liberacion"));
          //  ViewBag.NroActa = NroActa;

            return Json(acts, JsonRequestBehavior.AllowGet);

        }



        private List<ActIndexViewModel> GetActIndexFiltrado()
        {
            try
            {


                var lista = db.Acts.Where(x => x.Enable == true).Select(c => new { c.Id, c.FechaCarga, c.FechaInfraccion, c.NroActa, c.Dominio, c.EstadoVehiculo, c.DNI, c.Nombre, c.Apellido }).OrderByDescending(x => x.FechaInfraccion).OrderByDescending(x=>x.FechaCarga).Take(1000);
                ;


                List<ActIndexViewModel> acts = new List<ActIndexViewModel>();
                var liberations = db.Liberations.Where(x => x.Enable == true).ToList();

                foreach (var item in lista)
                {
                    ActIndexViewModel act = new ActIndexViewModel();
                    Liberation liberation = new Liberation();

                    //Busco si tiene un liberacion
                    liberation = liberations.Where(x => x.ActaId == item.Id).FirstOrDefault();

                    act.Id = item.Id;
                    act.NroActa = item.NroActa;
                    if (liberation != null)
                        act.NroLiberacion = liberation.NroLiberacion;

                    act.Apellido = item.Apellido;
                    act.DNI = item.DNI;
                    act.Dominio = item.Dominio;
                    act.Estado = item.EstadoVehiculo;
                    act.FechaCarga = item.FechaCarga;
                    act.FechaInfraccion = item.FechaInfraccion;

                    acts.Add(act);

                }

                return acts;
            }
            catch (Exception e)
            {

                throw;
            }

        }

        [HttpPost]
        public JsonResult GetActs()
        {
            try
            {

                List<ActIndexViewModel> acts = new List<ActIndexViewModel>();
                acts = GetActIndexFiltrado();
                 return Json(acts, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {

                throw;
            }
        }


        [HttpGet]
        public JsonResult GetDuplicates(int id, string nroActa)
        {

            try
            {
                var result = from c in db.Acts
                             where c.Id != id
                             && c.NroActa.ToUpper() == nroActa.ToUpper()
                             && c.Enable==true
                             && c.FechaCarga.Year == DateTime.Now.Year
                             select c;

                var responseObject = new
                {
                    responseCode = result.Count()
                };

                return Json(responseObject, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public JsonResult GetDatosDelInfractor(string dni)
        {
            Act act = new Act();
            InfractorViewModel infractor = new InfractorViewModel();
            try
            {
                act = db.Acts.Where(x => x.DNI == dni).FirstOrDefault();
                
                if (act!=null)
                {

Guardia Comunal/Views/Acts/Search.cshtml
@model IEnumerable<GuardiaComunal.Models.Act>

<table cellpadding="3" cellspacing="0" border="0" style="width: 67%; margin: 0 auto 2em auto; display: none ">
    <tbody>
        <tr id="filter_col2" data-column="1">
            <td align="center"><input type="text" class="column_filter" id="col1_filter"></td>
        </tr>
    </tbody>
</table>

@Html.Partial("_Table");

<!-- /#page-wrapper -->
<!-- /#wrapper -->
@section scripts {

    <script>

        function filterColumn(i) {
            $('#dataTables-Index').DataTable().column(i).search(
                $('#col' + i + '_filter').val()
            ).draw();
        }

    $(document).ready(function () {

        var AltaModificacion = '@ViewBag.AltaModificacion';
        var Baja = '@ViewBag.Baja';
        var Liberacion = '@ViewBag.Liberacion';        
        var NroActa = '@ViewBag.NroActa';

      //  $('#col1_filter').val(NroActa);
        

        $('input.column_filter').on('keyup click', function () {
            filterColumn($(this).parents('tr').attr('data-column'));
        });

         var table=  $('#dataTables-Index').DataTable({
              "ajax":
                  {
                  "url": "@Url.Action("GetActs2", "Acts", new { NroActa = "_Switch" })".replace("_Switch", NroActa),
                      type: "post",
                      data: JSON.stringify({
                          "NroActa": NroActa
                      }),
                      dataSrc: ""
                  },
              "columns": [
                  { "data": "id", defaultContent: '', "width": "100%" },
               { "data": "NroActa" },
               {
                   "data": "FechaInfraccion",
                   render: function (data, type, row) {
                       if (type === "sort" || type === "type") {
                           return data;
                       }
                       return moment(data).format("DD-MM-YYYY HH:mm");
                   }
               },
               { "data": "DNI" },
               { "data": "EstadoVehiculo" },
               { "data": "VehicleType.Descripcion" },
               { "data": "Dominio" },
               { "data": "NroMotor" },
               { "data": "NroChasis" },
               { "data": "VehicleBrand.Descripcion", defaultContent: '' },
               { "data": "VehicleModel.Descripcion", defaultContent: '' },
               { "data": "Color" },
               { "data": "TipoAgente" }
              ],
              rowId: 'Id',
              responsive: true,
              ordering: true,
              scrollX: true,
              "autoWidth": true,
              "fnCreatedRow": function (nRow, aData, iDataIndex) {
                  //Agrego las
                  // Add a class to the cell in the first column
                  $(nRow).children(':nth-child(1)').addClass('td-btn');

                  //Agrego el boton
                  if (AltaModificacion=='True')
                  {
                  //Modificar
                  $('td:eq(0)', nRow).append("<span class='fa fa-pencil span-btn' type='button' value='E' data-toggle='tooltip' data-placement='top' title='Modificar' id='btn_Editar' />");
                  }

                  if (Liberacion == 'True') {
                      //Liberar
                      if (aData.EstadoVehiculo == "Liberado") {
                          $('td:eq(0)', nRow).append("<span class='fa fa-check-square span-btn' type='button' value='C' data-toggle='tooltip' data-placement='top' title='Liberar' id='btn_Liberar_Edit'/> ");
                      }
                      else {
                          $('td:eq(0)', nRow).append("<span class='fa fa-check-square span-btn' type='button' value='C' data-toggle='tooltip' data-placement='top' title='Liberar' id='btn_Liberar'/> ");
                      }
                  }

                  if (Baja == 'True') {
                      //Borrar

                      $('td:eq(0)', nRow).append("<span data-toggle='modal' data-target='#eliminar-modal'><span class='fa fa-trash span-btn-dtl' type='button' value='D' data-toggle='tooltip' data-placement='top' title='Eliminar'/></span>");
                  }
              },
              "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                  if (aData.EstadoVehiculo == "Retenido") {
                      $('td', nRow).addClass('warning');
                  }
                  else if (aData.EstadoVehiculo == "Liberado") {
                      $('td', nRow).addClass('success');
                  }
                  else if (aData.EstadoVehiculo == "Compactado") {
                      $('td', nRow).addClass('danger');
                  }
              }

        });


         $('#col1_filter').trigger("click");


        // Setup - add a text input to each footer cell
         $('#dataTables-Index_wrapper tfoot th').each(function () {
            var title = $(this).text();
            if (title !== '') {
                $(this).html('<input type="text" placeholder=" ' + title + '" />');
            }
         });


        table.columns().every(function () {
            var that = this;


            $('input', this.footer()).on('keyup change', function () {
                if (that.search() !== this.value) {
                    that
                        .search(this.value)
                        .draw();
                }
            });
         });

    });

    $(document).on('click', '#btn_Editar', function () {
        var id = $(this).closest('tr').attr('id')
        var baseUrl = "@Url.Action("Edit", "Acts", new { id="ID"})";
        window.location.href = baseUrl.replace("ID",id);
    });

    $(document).on('click', '#btn_Liberar', function () {
        var id = $(this).closest('tr').attr('id')
        var baseUrl = "@Url.Action("Create", "Liberations", new { id="ID"})";
        window.location.href = baseUrl.replace("ID",id);
    });

    $(document).on('click', '#btn_Liberar_Edit', function () {
        var id = $(this).closest('tr').attr('id')
        var baseUrl = "@Url.Action("Edit", "Liberations", new { id="ID"})";
        window.location.href = baseUrl.replace("ID",id);
    });

        function Delete(a) {
            var id = $(a).closest('tr').attr('id')

            Lobibox.confirm({
                title: 'Atención',
                msg: "¿Esta seguro que desea eliminar el Acta?",
                callback: function ($this, type, ev) {
                    if (type === 'yes') {
                    $.ajax({
                    url: '@Url.Action("DeleteAct", "Acts")',
                    type: 'POST',
                    data: JSON.stringify({
                        "id": id
                    }),
                    contentType: 'application/json; charset=utf-8;',
                    success: function (result) {
                        $("#dataTables-Index").dataTable().fnReloadAjax();//Recargo la grilla
                        $("#div-loader").hide();
                        Lobibox.notify('success', {
                            title: 'Exito',
                            msg: 'Los cambios se han grabado correctamente.'
                        });
                    },
                    error: function (response) {
                        $("#div-loader").hide();
                            Lobibox.notify('error', {
                                title: 'Error',
                                msg: 'Ah ocurrido un error, intente nuevamente.'});
                        }
                     });
                    };
}

            });
        }

    </script>
}

Guardia Comunal/Views/Acts/_Table.cshtml
@using Guardia_Comunal.Helpers
@using Guardia_Comunal.ViewModel

<style>
    .td-btn {
        text-align: center !important;
        border-bottom: 1px solid #EAEAEA !important;
        font-size: 13px !important;
        padding-left: inherit !important;
        overflow: hidden !important;
        white-space: normal !important;
        height: auto !important;
        width: 400px !important;
        /* border-right-width: 0px; */
    }

    .span-btn {
        color: #666666;
        cursor: pointer;
        /* margin: 0px; */
        font-size: 18px;
        text-align: center;
        vertical-align: middle;
        width: 20px;
    }

    .span-btn-dtl {
        color: #9a3f3f;
        cursor: pointer;
        /* margin: 0px; */
        font-size: 18px;
        text-align: center;
        vertical-align: middle;
        width: 20px;
    }

    .dataTables-Index {
        table-layout: fixed;
    }

    .dataTable > thead > tr > th[class*="sort"]:after {
        content: "" !important;
    }

    .px200 {
        width: 200px;
        max-width: 200px;
        word-wrap: break-word;
    }

    .px100 {
        width: 10px !important;
        max-width: 50px;
        word-wrap: break-word;
    }

    .not-active {
        pointer-events: none;
        cursor: default;
        text-decoration: none;
        color: gainsboro;
    }
</style>
@if (PermissionViewModel.TienePermisoAcesso(WindowHelper.GetWindowId("Actas", "Buscar")))
{
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">

                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <table id="dataTables-Index" class="display nowrap table table-striped table-bordered table-hover" style="font-size:11px">
                            <thead>
                                <tr>
                                    <th class="px100">Acción</th>
                                    <th>Nro Acta</th>
                                    <th>Nro Liberacion</th>
                                    <th>Fecha Infracción</th>
                                    <th>Estado Vehiculo</th>
                                    <th>DNI</th>
                                    <th>Apellido</th>
                                    <th>Dominio</th>


                                </tr>
                            </thead>

                            @*<tfoot>
                                <tr>
                                    <th style="width: 100%"></th>
                                    <th id="thNroActa">Nro Acta</th>
                                    <th>Nro Liberacion</th>
                                    <th>Fecha Infracción</th>
                                    <th>Estado Vehiculo</th>
                                    <th>DNI</th>
                                    <th>Apellido</th>
                                    <th>Dominio</th>
                                </tr>
                            </tfoot>*@
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- Progress Loader -->
    <div id="div-loader" style="margin: 0px; padding: 0px; position: fixed; right: 0px; top: 0px; width: 100%; height: 100%; background-color: rgb(102, 102, 102); z-index: 30001; opacity: 0.8; display: none">
        <p style="position: absolute; color: White; top: 35%; left: 45%;">
            <img src="~/Images/loading.gif" alt="Loading..." />
        </p>
    </div>
}